app:
  name: "web_app"
  version: "1.0.1"
  port: 8080
  model: "dev"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "root"
  database: "mydb"

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: "0"

log:
  level: "Debug"
  filename: "log_all"

