app:
  name: "web_app"
  version: "1.0.0"
  description: "A web application based on KuangJia framework"
  author: "Your Name"
  author_email: "your_email@example.com"
  port: "8080"
  model: "dev"

mysql:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "root"
  database: "mydb"

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: "0"

log:
  level: "Debug"
  filename: "log_all"

